branches:
  only:
    - development
language: go
go_import_path: github.com/ethereum/go-ethereum
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      go: 1.9.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - apt-get install kubectl
      before_deploy:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker build -f Dockerfile -t clearmatics/dev-autonity
        - docker push clearmatics/dev-autonity
      deploy:
      provider: script
      script:
        - chmod +x scripts/deploy.sh 
        - scripts/deploy.sh
      on:
        branch: development