branches:
  only:
    - development
language: go
# go_import_path: github.com/ethereum/go-ethereum
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      go: 1.9.x
      # script:
        # - sudo modprobe fuse
        # - sudo chmod 666 /dev/fuse
        # - sudo chown root:$USER /etc/fuse.conf
        # - go run build/ci.go install
      install:
        - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
        - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
      # before_deployment:
      #   - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      #   - docker build -f Dockerfile -t clearmatics/dev-autonity
      #   - docker push clearmatics/dev-autonity
      deploy:
      provider: script
      script:
        - echo $AUTONITY_DEV_CA_CRT | base64 --decode -i > ${HOME}/ca.crt
        - kubectl config set-cluster dev01.autonity.io --embed-certs=true --server=${AUTONITY_DEV_CLUSTER_ENDPOINT} --certificate-authority=${HOME}/ca.crt
        - kubectl config set-credentials travis-default --token=$AUTONITY_DEV_USER_TOKEN
        - kubectl config set-context travis --cluster=dev01.autonity.io --user=travis-default --namespace=default
        - kubectl config use-context travis
        - kubectl config current-context
        - kubectl apply -f scripts/dev01/
        - pwd
        # - chmod +x scripts/deploy.sh 
        # - scripts/deploy.sh
      on:
        branch: development