branches:
  only:
    - development
language: go
# go_import_path: github.com/ethereum/go-ethereum
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      go: 1.9.x
      # script:
        # - sudo modprobe fuse
        # - sudo chmod 666 /dev/fuse
        # - sudo chown root:$USER /etc/fuse.conf
        # - go run build/ci.go install
      install:
        - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
        - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
      script:
        - echo $KCFG > | base64 --decode -i ${HOME}/config
        - kubectl --kubeconfig ${HOME}/config --context dev01.autonity.io get pods
        # - docker login -u $DOCKER_USER -p $DOCKER_PASS
        # - docker build . -t clearmatics/dev-autonity
        # - docker push clearmatics/dev-autonity
        # - echo $AUTONITY_DEV_CA_CRT | base64 --decode -i > ${HOME}/ca.crt
        # - kubectl config set-cluster dev01.autonity.io --embed-certs=true --server=${AUTONITY_DEV_CLUSTER_ENDPOINT} --certificate-authority=${HOME}/ca.crt
        # - kubectl config set-credentials travis-default --token=${AUTONITY_DEV_USER_TOKEN}
        # - kubectl config set-context travis --cluster=dev01.autonity.io --user=travis-default --namespace=default
        # - kubectl config use-context travis
        # - kubectl config current-context
        # - kubectl apply -v=4 -f scripts/dev01/
      on:
        branch: development