branches:
  only:
    - development
language: go
go_import_path: github.com/ethereum/go-ethereum
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      env: 
        - docker
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES
      success:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker build -f Dockerfile -t autonity
        - docker push autonity
      deploy:
      provider: script
      script: scripts/deploy.sh