apiVersion: v1
kind: Service
metadata:
  name: dev-autonity-04
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: rpc
      port: 30040
      targetPort: 30040
      nodePort: 30040
    - protocol: TCP
      name: listener
      port: 30343
      targetPort: 30343
      nodePort: 30343
  selector:
    app: dev-autonity-04
  clusterIP: 100.70.107.140
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev-autonity-04
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-autonity-04
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dev-autonity-04
        image: clearmatics/dev-autonity:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 30040
          name: rpc
        - containerPort: 30343
          name: p2p
        args:
          - "--nodiscover"
          - "--syncmode"
          - "fast"
          - "--datadir"
          - "/efs/04/"
          - "--networkid"
          - "9016"
          - "--rpc"
          - "--verbosity"
          - "9"
          - "--rpcaddr"
          - "0.0.0.0"
          - "--rpcport"
          - "30040"
          - "--port"
          - "30343"
          - "--nat"
          - "extip:34.245.26.76"
        volumeMounts:
          - name: pv-volume
            mountPath: /efs
      volumes:
        - name: pv-volume
          nfs:
            server: fs-f39fa73a.efs.eu-west-1.amazonaws.com
            path: /