apiVersion: v1
kind: Service
metadata:
  name: dev-autonity-02
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: rpc
      port: 30020
      targetPort: 30020
      nodePort: 30020
    - protocol: TCP
      name: listener
      port: 30323
      targetPort: 30323
      nodePort: 30323
  selector:
    app: dev-autonity-02
  clusterIP: 100.70.107.120
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev-autonity-02
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-autonity-02
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dev-autonity-02
        image: clearmatics/dev-autonity:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 30020
          name: rpc
        - containerPort: 30323
          name: p2p
        args:
          - "--nodiscover"
          - "--syncmode"
          - "fast"
          - "--datadir"
          - "/efs/02/"
          - "--networkid"
          - "9016"
          - "--rpc"
          - "--verbosity"
          - "9"
          - "--minerthreads"
          - "1"
          - "--mine"
          - "--unlock"
          - "0x8e17c05d9bee5c7b4d1daea8733388fe4f5fe1e1"
          - "--password"
          - "/efs/02/password"
          - "--maxpeers"
          - "5"
          - "--rpcport"
          - "30020"
          - "--rpcaddr"
          - "0.0.0.0"
          - "--port"
          - "30323"
          - "--nat"
          - "extip:34.245.26.76"
        volumeMounts:
          - name: pv-volume
            mountPath: /efs
      volumes:
        - name: pv-volume
          nfs:
            server: fs-f39fa73a.efs.eu-west-1.amazonaws.com
            path: /